### ISSUE TITLE
HTTP Manager Option Missing in Chrome

### ISSUE THREAD

**Issue by jonathanhickford** [sparkfun/phant-manager-sparkfun#2]
Viewing https://data.sparkfun.com/config in chrome doesn't show the HTTP option under 'Add Manager'.  On Chrome version 42.0.2311.90 m

![chrome](https://cloud.githubusercontent.com/assets/141340/7279257/7b8dc6d0-e912-11e4-9d1b-fc02bba14e7a.png)

IE and Firefox show the option.
![Firefox](https://cloud.githubusercontent.com/assets/141340/7279285/ad2e7644-e912-11e4-8f8a-64a4b4232e40.png)

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
