### ISSUE TITLE
Merge conflict markers were committed

### ISSUE THREAD

**Issue by rwaldron** [sparkfun/phant-manager-sparkfun#4]
Spotted in the readme.md file, committed here https://github.com/sparkfun/phant-manager-sparkfun/commit/0533e0577a465550652827e8ae551d22304645e8

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
